export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const LOGIN_USER = 'login_user'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_USER_FAIL = 'login_user_fail'

export const EMPLOYEE_UPDATED = 'employee_updated'
export const EMPLOYEE_CREATED = 'employee_created'
export const EMPLOYEE_FORM_CLEAR = 'employee_form_clear'
export const EMPLOYEES_FETCH_SUCCESS = 'employees_fetch_success'